/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>auto Building</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.autoBuilding#isAutobuilding <em>Autobuilding</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getautoBuilding()
 * @model
 * @generated
 */
public interface autoBuilding extends EObject
{
  /**
   * Returns the value of the '<em><b>Autobuilding</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Autobuilding</em>' attribute.
   * @see #setAutobuilding(boolean)
   * @see cs.queensu.ca.unity.UnityPackage#getautoBuilding_Autobuilding()
   * @model
   * @generated
   */
  boolean isAutobuilding();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.autoBuilding#isAutobuilding <em>Autobuilding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Autobuilding</em>' attribute.
   * @see #isAutobuilding()
   * @generated
   */
  void setAutobuilding(boolean value);

} // autoBuilding
