/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>project Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.projectPath#getProjPath <em>Proj Path</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getprojectPath()
 * @model
 * @generated
 */
public interface projectPath extends EObject
{
  /**
   * Returns the value of the '<em><b>Proj Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proj Path</em>' attribute.
   * @see #setProjPath(String)
   * @see cs.queensu.ca.unity.UnityPackage#getprojectPath_ProjPath()
   * @model
   * @generated
   */
  String getProjPath();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.projectPath#getProjPath <em>Proj Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proj Path</em>' attribute.
   * @see #getProjPath()
   * @generated
   */
  void setProjPath(String value);

} // projectPath
