/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Rotate#getDx <em>Dx</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Rotate#getDy <em>Dy</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.Rotate#getDz <em>Dz</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getRotate()
 * @model
 * @generated
 */
public interface Rotate extends EObject
{
  /**
   * Returns the value of the '<em><b>Dx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dx</em>' attribute.
   * @see #setDx(double)
   * @see cs.queensu.ca.unity.UnityPackage#getRotate_Dx()
   * @model
   * @generated
   */
  double getDx();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Rotate#getDx <em>Dx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dx</em>' attribute.
   * @see #getDx()
   * @generated
   */
  void setDx(double value);

  /**
   * Returns the value of the '<em><b>Dy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dy</em>' attribute.
   * @see #setDy(double)
   * @see cs.queensu.ca.unity.UnityPackage#getRotate_Dy()
   * @model
   * @generated
   */
  double getDy();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Rotate#getDy <em>Dy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dy</em>' attribute.
   * @see #getDy()
   * @generated
   */
  void setDy(double value);

  /**
   * Returns the value of the '<em><b>Dz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dz</em>' attribute.
   * @see #setDz(double)
   * @see cs.queensu.ca.unity.UnityPackage#getRotate_Dz()
   * @model
   * @generated
   */
  double getDz();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Rotate#getDz <em>Dz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dz</em>' attribute.
   * @see #getDz()
   * @generated
   */
  void setDz(double value);

} // Rotate
