/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Settings</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.Settings#getSettingsFilename <em>Settings Filename</em>}</li>
 * </ul>
 *
 * @see cs.queensu.ca.unity.UnityPackage#getSettings()
 * @model
 * @generated
 */
public interface Settings extends EObject
{
  /**
   * Returns the value of the '<em><b>Settings Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings Filename</em>' attribute.
   * @see #setSettingsFilename(String)
   * @see cs.queensu.ca.unity.UnityPackage#getSettings_SettingsFilename()
   * @model
   * @generated
   */
  String getSettingsFilename();

  /**
   * Sets the value of the '{@link cs.queensu.ca.unity.Settings#getSettingsFilename <em>Settings Filename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Settings Filename</em>' attribute.
   * @see #getSettingsFilename()
   * @generated
   */
  void setSettingsFilename(String value);

} // Settings
