/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity.impl;

import cs.queensu.ca.unity.UnityPackage;
import cs.queensu.ca.unity.autoBuilding;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>auto Building</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.impl.autoBuildingImpl#isAutobuilding <em>Autobuilding</em>}</li>
 * </ul>
 *
 * @generated
 */
public class autoBuildingImpl extends MinimalEObjectImpl.Container implements autoBuilding
{
  /**
   * The default value of the '{@link #isAutobuilding() <em>Autobuilding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAutobuilding()
   * @generated
   * @ordered
   */
  protected static final boolean AUTOBUILDING_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isAutobuilding() <em>Autobuilding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAutobuilding()
   * @generated
   * @ordered
   */
  protected boolean autobuilding = AUTOBUILDING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected autoBuildingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnityPackage.Literals.AUTO_BUILDING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isAutobuilding()
  {
    return autobuilding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAutobuilding(boolean newAutobuilding)
  {
    boolean oldAutobuilding = autobuilding;
    autobuilding = newAutobuilding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnityPackage.AUTO_BUILDING__AUTOBUILDING, oldAutobuilding, autobuilding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnityPackage.AUTO_BUILDING__AUTOBUILDING:
        return isAutobuilding();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnityPackage.AUTO_BUILDING__AUTOBUILDING:
        setAutobuilding((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnityPackage.AUTO_BUILDING__AUTOBUILDING:
        setAutobuilding(AUTOBUILDING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnityPackage.AUTO_BUILDING__AUTOBUILDING:
        return autobuilding != AUTOBUILDING_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (autobuilding: ");
    result.append(autobuilding);
    result.append(')');
    return result.toString();
  }

} //autoBuildingImpl
