/**
 * generated by Xtext 2.18.0.M3
 */
package cs.queensu.ca.unity.impl;

import cs.queensu.ca.unity.Rotate;
import cs.queensu.ca.unity.UnityPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cs.queensu.ca.unity.impl.RotateImpl#getDx <em>Dx</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.impl.RotateImpl#getDy <em>Dy</em>}</li>
 *   <li>{@link cs.queensu.ca.unity.impl.RotateImpl#getDz <em>Dz</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RotateImpl extends MinimalEObjectImpl.Container implements Rotate
{
  /**
   * The default value of the '{@link #getDx() <em>Dx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDx()
   * @generated
   * @ordered
   */
  protected static final double DX_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDx() <em>Dx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDx()
   * @generated
   * @ordered
   */
  protected double dx = DX_EDEFAULT;

  /**
   * The default value of the '{@link #getDy() <em>Dy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDy()
   * @generated
   * @ordered
   */
  protected static final double DY_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDy() <em>Dy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDy()
   * @generated
   * @ordered
   */
  protected double dy = DY_EDEFAULT;

  /**
   * The default value of the '{@link #getDz() <em>Dz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDz()
   * @generated
   * @ordered
   */
  protected static final double DZ_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDz() <em>Dz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDz()
   * @generated
   * @ordered
   */
  protected double dz = DZ_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RotateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnityPackage.Literals.ROTATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDx()
  {
    return dx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDx(double newDx)
  {
    double oldDx = dx;
    dx = newDx;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnityPackage.ROTATE__DX, oldDx, dx));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDy()
  {
    return dy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDy(double newDy)
  {
    double oldDy = dy;
    dy = newDy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnityPackage.ROTATE__DY, oldDy, dy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDz()
  {
    return dz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDz(double newDz)
  {
    double oldDz = dz;
    dz = newDz;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnityPackage.ROTATE__DZ, oldDz, dz));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnityPackage.ROTATE__DX:
        return getDx();
      case UnityPackage.ROTATE__DY:
        return getDy();
      case UnityPackage.ROTATE__DZ:
        return getDz();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnityPackage.ROTATE__DX:
        setDx((Double)newValue);
        return;
      case UnityPackage.ROTATE__DY:
        setDy((Double)newValue);
        return;
      case UnityPackage.ROTATE__DZ:
        setDz((Double)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnityPackage.ROTATE__DX:
        setDx(DX_EDEFAULT);
        return;
      case UnityPackage.ROTATE__DY:
        setDy(DY_EDEFAULT);
        return;
      case UnityPackage.ROTATE__DZ:
        setDz(DZ_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnityPackage.ROTATE__DX:
        return dx != DX_EDEFAULT;
      case UnityPackage.ROTATE__DY:
        return dy != DY_EDEFAULT;
      case UnityPackage.ROTATE__DZ:
        return dz != DZ_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dx: ");
    result.append(dx);
    result.append(", dy: ");
    result.append(dy);
    result.append(", dz: ");
    result.append(dz);
    result.append(')');
    return result.toString();
  }

} //RotateImpl
